language: ruby
rvm: 2.4
script:
  - bundle exec jekyll build
  - bundle exec rake test
after_success:
  - bundle exec rake git:push:static
deploy:
  - provider: s3
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: cul-s3-dlst-travis-dh-staging
    region: us-west-2
    skip_cleanup: true
    local_dir: _site
    on:
      branch: staging
  - provider: s3
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: cul-s3-dlst-travis-dh-prod
    region: us-west-2
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
